---

- name: Setup ssh_config
  template:
    src:      'ssh_config.j2'
    dest:     '{{ ssh_client__config_dir }}/ssh_config'
    owner:    root
    group:    root
    mode:     0644
    validate: '{{ "ssh -F %s -G > /dev/null" if _ssh_client__version is version_compare(6.7, ">") else "/usr/bin/env true %s" }}'

- include_tasks: configure-known-hosts.yml
  when: ssh_client__generate_known_hosts|bool
