---

- name: Check OpenSSH client version
  environment:
    LC_MESSAGES: 'C'
  shell: 'ssh -V 2>&1 | grep --only-matching --extended-regexp --regexp="OpenSSH_[a-z0-9.]+" | sed -re "s/^OpenSSH_([0-9]+\.[0-9]+).*/\1/"'
  register: _ssh_client__version
  changed_when: False
  check_mode: no

- name: "Setup {{ ssh_client__config_dir}}/ssh_config"
  template:
    src:   'ssh_config.j2'
    dest:  '{{ ssh_client__config_dir }}/ssh_config'
    owner: root
    group: root
    mode:  0644
    backup: yes
    validate: '{{ "ssh -F %s -G > /dev/null" if _ssh_client__version.stdout|version_compare("6.7", ">") else "true %s" }}'
