---

- name: Get installed OpenSSH version
  # noqa 306
  shell: >-
    /usr/bin/env ssh -V 2>&1
    | grep --only-matching --extended-regexp --regexp="OpenSSH_[a-z0-9\.]+"
  environment:
    LC_MESSAGES: C
  when: ansible_local.ssh_client.version_full is not defined
  changed_when: false
  check_mode: false
  register: _ssh_client__version_raw

- name: Create _ssh_client__version variable
  set_fact:
    _ssh_client__version: "{{
        (
          _ssh_client__version_raw.stdout
          |regex_replace('^OpenSSH_([0-9]+\\.[0-9]+).*', '\\1')
        ) if _ssh_client__version_raw is not skipped
        else ansible_local.ssh_client.version_full
      }}"

- name: Setup ssh_config
  template:
    src: ssh_config.j2
    dest: '{{ ssh_client__configuation_directory }}/ssh_config'
    owner: root
    group: root
    mode: 0644
    validate: '{{ ssh_client__configuration_validator }}'

- name: Include known hosts generation
  include_tasks: configure-known-hosts.yml
  when: ssh_client__generate_known_hosts|bool
  tags: ['ssh-client', 'ssh-client-configure']
