---
- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: ['ssh']

- name: Install the latest version of SSH Client
  package:
    name: '{{ ssh__package_name }}'
    state: latest
  tags: ['ssh']

- name: Check OpenSSH client version
  environment:
    LC_MESSAGES: 'C'
  shell: 'ssh -V 2>&1 | grep --only-matching --extended-regexp --regexp="OpenSSH_[a-z0-9.]+" | sed -re "s/^OpenSSH_([0-9]+\.[0-9]+).*/\1/"'
  register: ssh__register_version
  changed_when: False
  check_mode: no
  tags: ['ssh']

- name: Setup /etc/ssh/ssh_config
  template:
    src:    'etc/ssh/ssh_config.j2'
    dest:   '/etc/ssh/ssh_config'
    owner:  'root'
    group:  'root'
    mode:   '0644'
    backup: yes
    validate: '{{ "ssh -F %s -G > /dev/null" if ssh__register_version.stdout | version_compare("6.7", ">") else "true %s" }}'
  tags: ['ssh']
