---
# tasks file for ansible-ssh-client

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['ssh-client', 'ssh-client-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['ssh-client', 'ssh-client-configure']

- name: Optionally importing facts tasks
  include_tasks: facts.yml
  when: ssh_client__facts|bool
  tags: ['ssh-client', 'ssh-client-facts']
