---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian8
    image: turgon37/docker-debian8-ansible
    command: /lib/systemd/systemd
  - name: debian9
    image: turgon37/docker-debian9-ansible
    command: /lib/systemd/systemd
  - name: centos7
    image: turgon37/docker-centos7-ansible
    command: /usr/lib/systemd/systemd
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
